tap "homebrew/core"
tap "homebrew/bundle"
tap "burntsushi/ripgrep", "https://github.com/BurntSushi/ripgrep.git"
tap "beeftornado/rmtree"
brew "autoconf"
brew "bash"
brew "bash-completion@2"
brew "cowsay"
brew "ctags"
brew "imagemagick"
brew "dmtx-utils"
brew "figlet"
brew "git", args: ["with-perl"]
brew "pinentry"
brew "gnupg"
brew "go"
brew "jq"
brew "openssl"
brew "paperkey"
brew "perl"
brew "poppler"
brew "python"
brew "python@2"
brew "qrencode"
brew "tree"
brew "vim", args: ["with-override-system-vi"]
brew "ykman"
brew "zbar"
brew "burntsushi/ripgrep/ripgrep-bin"
